layout_spectrum: 0.6121417
color:
  saturation: 0.7647555
  brandStrength: 0.9637437
  lightness: 0.8549747
  rhythmicContrast: 0.9772344
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.4873524
name: Manuela Harding
